from channelvit.meta_arch.dino import DINO
from channelvit.meta_arch.linear_prob import LinearProb
from channelvit.meta_arch.supervised import Supervised
from channelvit.meta_arch.supervised_multihead import SupervisedMultihead
from channelvit.meta_arch.supervised_prob import SupervisedProb
from channelvit.meta_arch.correlation_computer import CorrelationComputer
from channelvit.meta_arch.supervised_multiclass import SupervisedMulticlass
