from channelvit.transformations.camelyon_dino import CamelyonAugmentationDino
from channelvit.transformations.cell_dino import CellAugmentationDino
from channelvit.transformations.imagenet_dino import ImagenetAugmentationDino
from channelvit.transformations.rgb import RGBAugmentation
from channelvit.transformations.cell import CellAugmentation
from channelvit.transformations.bigearth import BigEarthAugmentation
from channelvit.transformations.bigearth_aug import BigEarthMMAugmentation
