#This version implements the regular input channel dropout for channelvitt
name: 'samplev5channelvit_small'
args:
  patch_size: 16
  in_chans: 3
  input_drop: 0.0
  drop_path_rate: 0.1
  enable_sample: True
