NICKNAME="supervised_v3vit_small_rxrx1_bs_256_fp32.sh"

python amlssl/main/main_supervised.py \
wandb.project="amlssl-supervised" \
nickname="${NICKNAME}" \
trainer.devices=8 \
trainer.precision=32 \
trainer.max_epochs=100 \
trainer.default_root_dir="s3://insitro-user/yujia/checkpoints/${NICKNAME}" \
meta_arch/backbone=v3vit_small \
meta_arch.target='sirna_id' \
meta_arch.backbone.args.in_chans=3 \
meta_arch.backbone.args.input_drop=0 \
meta_arch.num_classes=1139 \
data@train_data=rxrx \
data@val_data_dict=[rxrx_idtest,rxrx_test] \
train_data.rxrx.loader.num_workers=64 \
train_data.rxrx.loader.batch_size=32 \
train_data.rxrx.loader.drop_last=True \
train_data.rxrx.args.channels=[0,1,2] \
val_data_dict.rxrx_idtest.loader.num_workers=64 \
val_data_dict.rxrx_idtest.loader.batch_size=32 \
val_data_dict.rxrx_idtest.loader.drop_last=False \
val_data_dict.rxrx_idtest.args.channels=[0,1,2] \
val_data_dict.rxrx_test.loader.num_workers=64 \
val_data_dict.rxrx_test.loader.batch_size=32 \
val_data_dict.rxrx_test.loader.drop_last=False \
val_data_dict.rxrx_test.args.channels=[0,1,2] \
transformations@train_transformations=cell_rxrx \
transformations@val_transformations=cell_rxrx
