NICKNAME="supervised_v3vit_small_mixed_0.75_channels_jumpcp_bs_256_fp32_rerun_0"

python amlssl/main/main_supervised.py \
wandb.project="amlssl-supervised" \
nickname="${NICKNAME}" \
trainer.devices=8 \
trainer.precision=32 \
trainer.max_epochs=100 \
trainer.default_root_dir="s3://insitro-user/yujia/checkpoints/${NICKNAME}" \
trainer.accumulate_grad_batches=1 \
meta_arch/backbone=v3vit_small \
meta_arch.backbone.args.in_chans=8 \
meta_arch.target='label' \
meta_arch.num_classes=161 \
data@train_data=[jumpcp_fluro,jumpcp_fluro_bright] \
data@val_data_dict=[jumpcp_val,jumpcp_test] \
train_data.jumpcp_fluro.loader.num_workers=32 \
train_data.jumpcp_fluro.loader.batch_size=16 \
train_data.jumpcp_fluro.loader.drop_last=True \
train_data.jumpcp_fluro.args.channels=[0,1,2,3,4] \
train_data.jumpcp_fluro.args.split="fluro_0.75" \
train_data.jumpcp_fluro.args.upsample=1 \
train_data.jumpcp_fluro.args.scale=1.6 \
train_data.jumpcp_fluro.args.channel_mask=True \
train_data.jumpcp_fluro_bright.loader.num_workers=32 \
train_data.jumpcp_fluro_bright.loader.batch_size=16 \
train_data.jumpcp_fluro_bright.loader.drop_last=True \
train_data.jumpcp_fluro_bright.args.channels=[0,1,2,3,4,5,6,7] \
train_data.jumpcp_fluro_bright.args.split="fluro_bright_0.75" \
train_data.jumpcp_fluro_bright.args.upsample=1 \
train_data.jumpcp_fluro_bright.args.channel_mask=True \
val_data_dict.jumpcp_val.loader.num_workers=32 \
val_data_dict.jumpcp_val.loader.batch_size=32 \
val_data_dict.jumpcp_val.loader.drop_last=False \
val_data_dict.jumpcp_val.args.channels=[0,1,2,3,4,5,6,7] \
val_data_dict.jumpcp_test.loader.num_workers=32 \
val_data_dict.jumpcp_test.loader.batch_size=32 \
val_data_dict.jumpcp_test.loader.drop_last=False \
val_data_dict.jumpcp_test.args.channels=[0,1,2,3,4,5,6,7] \
transformations@train_transformations=cell \
transformations@val_transformations=cell

python amlssl/main/main_supervised.py \
wandb.project="amlssl-supervised" \
nickname="${NICKNAME}-evaluation-fluro" \
trainer.devices=8 \
trainer.precision=32 \
trainer.max_epochs=100 \
trainer.default_root_dir="s3://insitro-user/yujia/checkpoints/${NICKNAME}" \
trainer.accumulate_grad_batches=1 \
meta_arch/backbone=vit_small \
meta_arch.backbone.args.in_chans=8 \
meta_arch.target='label' \
meta_arch.num_classes=161 \
data@train_data=[jumpcp_fluro] \
data@val_data_dict=[jumpcp_test] \
train_data.jumpcp_fluro.loader.num_workers=32 \
train_data.jumpcp_fluro.loader.batch_size=16 \
train_data.jumpcp_fluro.loader.drop_last=True \
train_data.jumpcp_fluro.args.channels=[0,1,2,3,4] \
train_data.jumpcp_fluro.args.split="fluro_0.75" \
train_data.jumpcp_fluro.args.upsample=1 \
train_data.jumpcp_fluro.args.channel_mask=True \
train_data.jumpcp_fluro.args.scale=1.6 \
val_data_dict.jumpcp_test.loader.num_workers=32 \
val_data_dict.jumpcp_test.loader.batch_size=32 \
val_data_dict.jumpcp_test.loader.drop_last=False \
val_data_dict.jumpcp_test.args.channels=[0,1,2,3,4,5,6,7] \
val_data_dict.jumpcp_test.args.scale=1.6 \
transformations@train_transformations=cell \
transformations@val_transformations=cell \
val_transformations.args.channel_mask=[5,6,7] \
checkpoint="s3://insitro-user/yujia/checkpoints/${NICKNAME}/epoch\\=99"

python amlssl/main/main_supervised.py \
wandb.project="amlssl-supervised" \
nickname="${NICKNAME}-evaluation-all" \
trainer.devices=8 \
trainer.precision=32 \
trainer.max_epochs=100 \
trainer.default_root_dir="s3://insitro-user/yujia/checkpoints/${NICKNAME}" \
trainer.accumulate_grad_batches=1 \
meta_arch/backbone=vit_small \
meta_arch.backbone.args.in_chans=8 \
meta_arch.target='label' \
meta_arch.num_classes=161 \
data@train_data=[jumpcp_fluro] \
data@val_data_dict=[jumpcp_test] \
train_data.jumpcp_fluro.loader.num_workers=32 \
train_data.jumpcp_fluro.loader.batch_size=16 \
train_data.jumpcp_fluro.loader.drop_last=True \
train_data.jumpcp_fluro.args.channels=[0,1,2,3,4] \
train_data.jumpcp_fluro.args.split="fluro_0.75" \
train_data.jumpcp_fluro.args.upsample=1 \
train_data.jumpcp_fluro.args.channel_mask=True \
val_data_dict.jumpcp_test.loader.num_workers=32 \
val_data_dict.jumpcp_test.loader.batch_size=32 \
val_data_dict.jumpcp_test.loader.drop_last=False \
val_data_dict.jumpcp_test.args.channels=[0,1,2,3,4,5,6,7] \
transformations@train_transformations=cell \
transformations@val_transformations=cell \
checkpoint="s3://insitro-user/yujia/checkpoints/${NICKNAME}/epoch\\=99"


NICKNAME="supervised_v3vit_small_mixed_0.75_channels_jumpcp_bs_256_fp32_rerun_1"

python amlssl/main/main_supervised.py \
wandb.project="amlssl-supervised" \
nickname="${NICKNAME}" \
trainer.devices=8 \
trainer.precision=32 \
trainer.max_epochs=100 \
trainer.default_root_dir="s3://insitro-user/yujia/checkpoints/${NICKNAME}" \
trainer.accumulate_grad_batches=1 \
meta_arch/backbone=v3vit_small \
meta_arch.backbone.args.in_chans=8 \
meta_arch.target='label' \
meta_arch.num_classes=161 \
data@train_data=[jumpcp_fluro,jumpcp_fluro_bright] \
data@val_data_dict=[jumpcp_val,jumpcp_test] \
train_data.jumpcp_fluro.loader.num_workers=32 \
train_data.jumpcp_fluro.loader.batch_size=16 \
train_data.jumpcp_fluro.loader.drop_last=True \
train_data.jumpcp_fluro.args.channels=[0,1,2,3,4] \
train_data.jumpcp_fluro.args.split="fluro_0.75" \
train_data.jumpcp_fluro.args.upsample=1 \
train_data.jumpcp_fluro.args.scale=1.6 \
train_data.jumpcp_fluro.args.channel_mask=True \
train_data.jumpcp_fluro_bright.loader.num_workers=32 \
train_data.jumpcp_fluro_bright.loader.batch_size=16 \
train_data.jumpcp_fluro_bright.loader.drop_last=True \
train_data.jumpcp_fluro_bright.args.channels=[0,1,2,3,4,5,6,7] \
train_data.jumpcp_fluro_bright.args.split="fluro_bright_0.75" \
train_data.jumpcp_fluro_bright.args.upsample=1 \
train_data.jumpcp_fluro_bright.args.channel_mask=True \
val_data_dict.jumpcp_val.loader.num_workers=32 \
val_data_dict.jumpcp_val.loader.batch_size=32 \
val_data_dict.jumpcp_val.loader.drop_last=False \
val_data_dict.jumpcp_val.args.channels=[0,1,2,3,4,5,6,7] \
val_data_dict.jumpcp_test.loader.num_workers=32 \
val_data_dict.jumpcp_test.loader.batch_size=32 \
val_data_dict.jumpcp_test.loader.drop_last=False \
val_data_dict.jumpcp_test.args.channels=[0,1,2,3,4,5,6,7] \
transformations@train_transformations=cell \
transformations@val_transformations=cell

python amlssl/main/main_supervised.py \
wandb.project="amlssl-supervised" \
nickname="${NICKNAME}-evaluation-fluro" \
trainer.devices=8 \
trainer.precision=32 \
trainer.max_epochs=100 \
trainer.default_root_dir="s3://insitro-user/yujia/checkpoints/${NICKNAME}" \
trainer.accumulate_grad_batches=1 \
meta_arch/backbone=vit_small \
meta_arch.backbone.args.in_chans=8 \
meta_arch.target='label' \
meta_arch.num_classes=161 \
data@train_data=[jumpcp_fluro] \
data@val_data_dict=[jumpcp_test] \
train_data.jumpcp_fluro.loader.num_workers=32 \
train_data.jumpcp_fluro.loader.batch_size=16 \
train_data.jumpcp_fluro.loader.drop_last=True \
train_data.jumpcp_fluro.args.channels=[0,1,2,3,4] \
train_data.jumpcp_fluro.args.split="fluro_0.75" \
train_data.jumpcp_fluro.args.upsample=1 \
train_data.jumpcp_fluro.args.channel_mask=True \
train_data.jumpcp_fluro.args.scale=1.6 \
val_data_dict.jumpcp_test.loader.num_workers=32 \
val_data_dict.jumpcp_test.loader.batch_size=32 \
val_data_dict.jumpcp_test.loader.drop_last=False \
val_data_dict.jumpcp_test.args.channels=[0,1,2,3,4,5,6,7] \
val_data_dict.jumpcp_test.args.scale=1.6 \
transformations@train_transformations=cell \
transformations@val_transformations=cell \
val_transformations.args.channel_mask=[5,6,7] \
checkpoint="s3://insitro-user/yujia/checkpoints/${NICKNAME}/epoch\\=99"

python amlssl/main/main_supervised.py \
wandb.project="amlssl-supervised" \
nickname="${NICKNAME}-evaluation-all" \
trainer.devices=8 \
trainer.precision=32 \
trainer.max_epochs=100 \
trainer.default_root_dir="s3://insitro-user/yujia/checkpoints/${NICKNAME}" \
trainer.accumulate_grad_batches=1 \
meta_arch/backbone=vit_small \
meta_arch.backbone.args.in_chans=8 \
meta_arch.target='label' \
meta_arch.num_classes=161 \
data@train_data=[jumpcp_fluro] \
data@val_data_dict=[jumpcp_test] \
train_data.jumpcp_fluro.loader.num_workers=32 \
train_data.jumpcp_fluro.loader.batch_size=16 \
train_data.jumpcp_fluro.loader.drop_last=True \
train_data.jumpcp_fluro.args.channels=[0,1,2,3,4] \
train_data.jumpcp_fluro.args.split="fluro_0.75" \
train_data.jumpcp_fluro.args.upsample=1 \
train_data.jumpcp_fluro.args.channel_mask=True \
val_data_dict.jumpcp_test.loader.num_workers=32 \
val_data_dict.jumpcp_test.loader.batch_size=32 \
val_data_dict.jumpcp_test.loader.drop_last=False \
val_data_dict.jumpcp_test.args.channels=[0,1,2,3,4,5,6,7] \
transformations@train_transformations=cell \
transformations@val_transformations=cell \
checkpoint="s3://insitro-user/yujia/checkpoints/${NICKNAME}/epoch\\=99"
